[deps]
BasisMatrices = "08854c51-b66b-5062-a90d-8e7ae4547a49"
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DataVoyager = "5721bf48-af8e-5845-8445-c9e18126e773"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FixedEffectModels = "9d5cd8c9-2029-5cab-9928-427838db53e3"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IntervalRootFinding = "d2bf35a9-74e0-55ec-b149-d360ff49b807"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OptimTestProblems = "cec144fc-5a64-5bc6-99fb-dde8f63e154c"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuantEcon = "fcd29c91-0bd7-5a09-975d-7ac3f643a60c"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RegressionTables = "d519eb52-b820-54da-95a6-98e1306fdade"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"
